### ISSUE TITLE
[demo-materialize] Problem with require.extensions in Node 8+

### ISSUE THREAD

**Issue by szewczyk-it** [aurelia-ui-toolkits/aurelia-materialize-bridge#455]
* node v8.1.4
* npm 5.3.0
* jspm 0.16.15 (Running against local jspm install)
* Windows 10 x64
```bash
gulp watch
```
returns
```
C:\Users\user\Documents\aurelia\demo-materialize\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (C:\Users\user\Documents\aurelia\demo-materialize\node_modules\require-dir\index.js:93:37)
    at Object.<anonymous> (C:\Users\user\Documents\aurelia\demo-materialize\gulpfile.js:3:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
```
Function `hasOwnProperty` is [deprecated](https://nodejs.org/api/globals.html#globals_require_extensions).

Solutions:
* Downgrade node to 6.11.1
* change in `package.json` version of the require-dir: `"require-dir": "^0.3.2"` ([this issue](https://github.com/aseemk/requireDir/pull/48))

**Comment by Thanood** [comment]
Interesting, I don't have that problem with node 8..
Even more interesting: it is already at `"require-dir": "^0.3.2"`: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L102

Any idea what happens there?

What I did when upgrading from node 6 to 8 was, remove the node_modules and reinstall..

**Comment by szewczyk-it** [comment]
Sorry for inaccurate explanation.
In title I worte [demo-materialize] - I mean [this file](https://github.com/aurelia-ui-toolkits/demo-materialize/blob/master/package.json#L66)

**Comment by szewczyk-it** [comment]
Because as you know from GutBook [discussion](https://www.gitbook.com/book/aurelia-ui-toolkits/materialize-bridge-docs/discussions/16) I have problem with installation this bridge and installation of [demo-materialize](https://github.com/aurelia-ui-toolkits/demo-materialize) as skeleton is fine  ;-)

**Comment by Thanood** [comment]
Ah okay, you cloned `demo-materialize`.. Okay, I can change it there, too.
I will yet have to read your post in gitbook since I'll have to go in a few minutes. But we'll get this straight.. 😃
